;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   do. sep. 1 2019
; Processor: PIC16F877A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f877a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
CBLOCK 20h
decenas
unidades
temp
Temperatura
Temp_usuario
ENDC
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
      
org 4
      goto LeerTemperatura
      
      
#define siguiente   PORTB,0
#define incrementar PORTB,1
#define decrementar PORTB,2
;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      call LCD_Inicializa
;================= Inicializa los pines I/O =========================      
      bsf STATUS,RP0
      bcf STATUS,RP1
      bsf siguiente   
      bsf incrementar 
      bsf decrementar 
      bsf OPTION_REG,NOT_RBPU
      bcf OPTION_REG,INTEDG
      bcf TRISD,0 ;motor, (calentador)
      bsf TRISC, 4 ; Pin de entrada para el sensor DS18B20
      
      bcf STATUS,RP0
;====================================================================
      movlw b'10010000'
      movwf INTCON
      goto FinMensajes
;================= Declaracion de Mensajes ==========================
Mensajes
      addwf PCL,F
m1
      DT "Empezar?", 0x00
m2
      DT "Pres. SIGUIENTE!", 0x00
m3
      DT "Ingrese", 0x00
m4
      DT "dos numeros:", 0x00
m5
      DT "Usuario:", 0x00
m6
      DT "Sensor:", 0x00

Signo 
      DT "-", 0x00
Punto 
      DT ".", 0x00

FinMensajes



Loop  
      call LCD_Borra                      
      movlw m1
      call LCD_Mensaje
      call LCD_Linea2               
      movlw m2
      call LCD_Mensaje
      sleep
      goto  Loop

      

      
      

LeerTemperatura
      clrf decenas
      clrf unidades
      
      call LCD_Borra                
      movlw m3
      call LCD_Mensaje
      call LCD_Linea2
      movlw m4
      call LCD_Mensaje
      movlw .12
      call LCD_PosicionLinea2
      movf decenas,w
      call BIN_a_BCD
      call LCD_Nibble
      call ReboteSiguiente
N_Decenas
      btfss siguiente
      goto ImprimirUnidades
      btfss incrementar
      goto IncDecenas
      btfss decrementar
      goto DecDecenas
      goto N_Decenas

ImprimirUnidades
      movlw .13
      call LCD_PosicionLinea2
      movf unidades,w
      call BIN_a_BCD
      call LCD_Nibble
      call ReboteSiguiente
      
N_Unidades
      btfss siguiente
      goto PrepararDecenas
      btfss incrementar
      goto IncUnidades
      btfss decrementar
      goto DecUnidades
      goto N_Unidades

PrepararDecenas
      call ReboteSiguiente
      call CicloDecenas
      
      call LCD_Borra                
      movlw m5
      call LCD_Mensaje
      call Sumador                ;suma las unidades con las decenas       
      call BIN_a_BCD 
      call LCD_ByteCompleto
      call LCD_Linea2
      movlw m6
      call LCD_Mensaje

NivelarTemperatura			
      movlw .4
      movwf temp
cicloTemp
      call DS18B20_Inicializa
      call DS18B20_LeeTemperatura
      call Retardo_200ms
      decfsz temp,F
      goto cicloTemp
      call Retardo_1s
      
VerificaTempSensor
      movlw .7
      call LCD_PosicionLinea2
      call DS18B20_Inicializa
      call DS18B20_LeeTemperatura
      movwf Temperatura             ;mueve el valor absoluto de la temperatura
      btfss DS18B20_TemperaturaSigno,0
      goto Temp_Pos
Temp_Neg
      movlw Signo
      call LCD_Mensaje
Temp_Pos
      movf Temperatura,W         ;cargamos la el valor absoluto de la temperatura en w
      call BIN_a_BCD    
      movf BCD_Centenas,W                 
      call LCD_Nibble
      movf BCD_Decenas,W
      call LCD_Nibble
      movf BCD_Unidades,W
      call LCD_Nibble
      call Temp_Punto               ;imprime punto
      movf DS18B20_TemperaturaDecimal,W   ;imprime valor decimal de la temperatura
      call BIN_a_BCD
      call LCD_ByteCompleto
      
CompararTemps
      movf Temp_usuario,W         ;A->TemperaturaSensor - B->TemperaturaUsuario
      subwf Temperatura,W
      btfss STATUS,C
      goto LeerZ 
      btfss STATUS,Z
      goto A_MAYOR_B
      goto A_IGUAL_B
      
A_MENOR_B
      goto ON
      
A_MAYOR_B
      goto OFF 
      
A_IGUAL_B       
       goto OFF    
LeerZ      
      btfss STATUS,Z
      goto A_MENOR_B
      goto FinCompararTemps
      
ON
      bsf PORTD,0
      goto FinCompararTemps

OFF  
      bcf PORTD,0
      goto FinLeerTemperatura

FinCompararTemps
  
      call Retardo_2s
      goto VerificaTempSensor
      
FinLeerTemperatura
      bcf INTCON,INTF
      retfie
      
IncDecenas
      call ReboteIncrementar
      movlw .9
      subwf decenas,W
      btfss STATUS,C
      goto AddDecenas 
      btfss STATUS,Z
      goto AddDecenas
      clrf decenas
      goto FinIncDecenas
AddDecenas
      incf decenas,F
FinIncDecenas 
      movlw .12
      call LCD_PosicionLinea2
      movf decenas,w
      call BIN_a_BCD
      call LCD_Nibble
      goto N_Decenas
      
DecDecenas
      call ReboteDecrementar
      movlw .0
      subwf decenas,W
      btfss STATUS,C
      goto SubDecenas 
      btfss STATUS,Z
      goto SubDecenas
      movlw .9
      movwf decenas
      goto FinDecDecenas
SubDecenas
      decf decenas,F
FinDecDecenas 
      movlw .12
      call LCD_PosicionLinea2
      movf decenas,w
      call BIN_a_BCD
      call LCD_Nibble
      goto N_Decenas

IncUnidades
      call ReboteIncrementar
      movlw .9
      subwf unidades,W
      btfss STATUS,C
      goto AddUnidades
      btfss STATUS,Z
      goto AddUnidades
      clrf unidades
      goto FinIncUnidades
AddUnidades
      incf unidades,F
FinIncUnidades 
      movlw .13
      call LCD_PosicionLinea2
      movf unidades,w
      call BIN_a_BCD
      call LCD_Nibble
      goto N_Unidades
      
DecUnidades
      call ReboteDecrementar
      movlw .0
      subwf unidades,W
      btfss STATUS,C
      goto SubUnidades
      btfss STATUS,Z
      goto SubUnidades
      movlw .9
      movwf unidades
      goto FinDecUnidades
SubUnidades
      decf unidades,F
FinDecUnidades 
      movlw .13
      call LCD_PosicionLinea2
      movf unidades,w
      call BIN_a_BCD
      call LCD_Nibble
      goto N_Unidades
 

Temp_Punto
      movlw Punto
      call LCD_Mensaje
      return
      
Sumador
      movf decenas,W
      addwf unidades,W
      movwf Temp_usuario
      ;devuelve la suma en W
      return


CicloDecenas
      movf decenas,W
      movwf temp
      clrf decenas
      movlw .0
      subwf temp
      btfss STATUS,C
      goto Ciclo
      btfss STATUS,Z
      goto Ciclo
      clrf decenas
      goto FinCicloDecenas
Ciclo
				    ;si se ingresa 3 como decenas, al final del ciclo se guardara
      decfsz temp,F		    ;30 en las decenas
      goto CicloIncDecenas
      movlw .10
      addwf decenas
      goto FinCicloDecenas
CicloIncDecenas
      movlw .10			    
      addwf decenas 
      goto Ciclo
FinCicloDecenas
      return 
      
#include bin_bcd.inc
#include Retardos.inc
#include Teclado.inc
#include LCD_4BIT.inc
#include lcd_mens.inc
#include Bus1Linea.inc
#include DS18B20.inc
#include Rebotes.inc
;====================================================================
      END
